### ISSUE TITLE
Where is the latest App Insights C++ SDK?

### ISSUE THREAD

**Issue by bangbingsyb** [Microsoft/ApplicationInsights-CPP#16]
Hi team,

I'm looking into developing IIS native App Insights instrumentation - basically raise App Insights metrics inside IIS native modules instead of in ASP.NET modules, handlers, or apps. Therefore, I'm looking for App Insight C++ SDK, and found this project.

However, based on the project description, it looks like it has been deprecated. I'm wondering where can I find the latest C++ SDK for App Insights?

Thanks in advance,
Yanbing

**Comment by SergeyKanzhelev** [comment]
I replied on internal mail thread. Closing it here

**Comment by Networkdog** [comment]
Any update on this? Where can I find the latest C++ SDK project?
