### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [Microsoft/ApplicationInsights-CPP#2]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null) in [functions like "Utils::SafeDelete" and "Utils::SafeDeleteArray"](https://github.com/Microsoft/ApplicationInsights-CPP/blob/beed1ecede784803b656b88bd1ae41d06ea0b19b/src/core/common/Utils.h#L28).

**Comment by HolgerStrauss** [comment]
I agree. However, I'd really like to see these functions being eliminated completely. Utils::SafeDeleteArray is not used in the project anyhow and Utils::SafeDelete is used in the destructor of TelemetryClient only. In modern C++, manager objects like std::unique_ptr or std::shared_ptr should be used instead.
(https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rr-newdelete, https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rr-immediate-alloc).
I can offer to provide appropriate changes to the source code if Microsoft is willing to accept external contributions (currently having one pending pull request with a minor change and hoping that it will be accepted...).

**Comment by crystk** [comment]
We are definitely willing to accept external contributions.  You will need to sign the CLA before we can merge your changes in.  Thank you.

**Comment by HolgerStrauss** [comment]
Just added a pull request to fix this issue. CLA was already signed on Nov. 11.

**Comment by crystk** [comment]
Thank you for the contribution.  It is much appreciated.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/Microsoft/ApplicationInsights-CPP/commit/fa8dbe0c908e88b35a6b7684da0ace8c68929f6e).
