### ISSUE TITLE
TrackEvent overloaded function not available

### ISSUE THREAD

**Issue by codelegger** [Microsoft/ApplicationInsights-CPP#4]
I am updating my app from win8.1 to uwp and i am using this function from 
**Namespace:   Microsoft.ApplicationInsights**
void TrackEvent(
    String^ eventName,
    IDictionary<String^, String^>^ properties = null,
    IDictionary<String^, double>^ metrics = null
)

> Why this function is not available in ApplicationInsight-cpp or any alternative ??

p.s:https://msdn.microsoft.com/en-us/library/dn817583.aspx

**Comment by crystk** [comment]
You can use:
void TrackEvent(const std::wstring& eventName, const wstring_wstring_map& properties, const std::map<std::wstring, double>& measurements);
