### ISSUE TITLE
Upgrade the project to support Visual Studio 2015 Projects

### ISSUE THREAD

**Issue by keiichi-morisato** [Microsoft/ApplicationInsights-CPP#5]
The project as it stands is configured for Visual Studio 2013. While we can use it from VS2015, it would be best to add VS2015 and x64 to the project solution.

I'm willing to tackle this issue.

**Comment by crystk** [comment]
Thank you for fixing this issue.  I have merged your changes.

**Comment by keiichi-morisato** [comment]
I added the package file as well minus the actual nuget upload script. We are using this in our Windows x64 nt-service project and want to use it as a nuget. How should I proceed? I obviously cannot upload our ApiKey since it is a private repository.
